/* Generated by scripts/build-status-data.py in the product-hub repo.
   Do not edit by hand -- edit resources/roadmap.yml there instead. */
window.STATUS_DATA = {
  "schema": 2,
  "timeline": {
    "start": "2026-05-01",
    "end": "2026-11-30",
    "today": "2026-08-26",
    "pto": [],
    "pto_unresolved": []
  },
  "generated_at": "2026-08-26T21:44:33+00:00",
  "quarter": "Q3-2026",
  "note": "Milestone progress is measured against two independent sources: the PRD requirement set (what we said we'd build) and Jira (what the team has ticketed and done). Where they disagree, the page says so rather than picking one.",
  "jira_connected": true,
  "rag_rule": {
    "green": "No warnings raised",
    "amber": "Target within 14 days with more than 25% still open, or work not mapped to a milestone",
    "red": "Target passed and not complete, or no tickets exist within 14 days of target"
  },
  "features": [
    {
      "key": "asam-v4",
      "name": "ASAM 4th Edition",
      "short": "ASAM 4th Edition",
      "blurb": "The 4th Edition of the ASAM criteria, as a working assessment a clinician would choose over paper — not a compliance checkbox bolted onto the 3rd.",
      "owner": "Christian Carlstrom",
      "eng": "Franco Agresta",
      "status": "In Development",
      "prd": {
        "title": "ASAM 4th Edition PRD",
        "url": "https://docs.google.com/document/d/1o7SZnN4DoP_2aTKtp_xJxbzTZJWJymwr/edit",
        "file_id": "1o7SZnN4DoP_2aTKtp_xJxbzTZJWJymwr"
      },
      "prototype": "https://christianjamesc.github.io/ICANotesProduct/asam-4th-edition/index.html",
      "epic": "CLN-4023",
      "epic_url": "https://icanotes.atlassian.net/browse/CLN-4023",
      "milestones": [
        {
          "id": "M1",
          "claim": "A pilot practice can complete a 4th Edition assessment",
          "why": "A real practice does a real assessment end to end, and we can hand an auditor the blank template. That's the June problem, closed. Nothing derived, no grid — deliberately the smallest thing that's genuinely usable.",
          "must_be_true": [
            "Create V3 Permission and Flag, so practices can sunset V3 and allow users to only be able to use V4\n",
            "Remove the V4 Intoxication Severity / Withdrawal Risk & Complexity 0–2 ratings being retired on v4 charts\n",
            "Feature flag for practice enablement, per-permission grant of 3rd, 4th or both, and the edition prompt at note creation\n",
            "The v4 dimension screens: subdimension rating columns, relocated content, new shrub buttons\n",
            "Level of care selected by the clinician from the 4th Edition list, shown under the dimension ratings / recommendation tab and the recommended level of care dropdown\n",
            "Compiled note and printable template"
          ],
          "target": "2026-09-19",
          "target_confirmed": false,
          "days_left": 24,
          "notes": [
            "REQ-D1-8 straddles: \"edition selection\" belongs here, \"shrub picker redesign\" belongs in M2. Assigned to M1 — split it if that's wrong.",
            "REQ-D2-2 (Vital Signs) sits here on the basis that M1 uses the Vital Signs shrub content exactly as it exists today; the redesign is M3."
          ],
          "open_questions": [
            "How does this behave for C2P for v3 and V4? It should just be imported notes."
          ],
          "reqs": {
            "total": 57,
            "no_work": 7,
            "removal": 12,
            "open": 38,
            "work": 50,
            "missing": 0,
            "items": {
              "done": [
                {
                  "id": "REQ-N-1",
                  "title": "Compiled note behaves as it does today",
                  "state": "No change",
                  "group": "NOTE"
                },
                {
                  "id": "REQ-D1-6",
                  "title": "Risk Rating — global, v3 only",
                  "state": "Keep v3",
                  "group": "D1"
                },
                {
                  "id": "REQ-D2-9",
                  "title": "Existing v3 buttons stay intact",
                  "state": "Keep v3",
                  "group": "D2"
                },
                {
                  "id": "REQ-D3-11",
                  "title": "Existing v3 buttons stay intact",
                  "state": "Keep v3",
                  "group": "D3"
                },
                {
                  "id": "REQ-D4-8",
                  "title": "Existing v3 buttons stay intact",
                  "state": "Keep v3",
                  "group": "D4"
                },
                {
                  "id": "REQ-D5-11",
                  "title": "Existing v3 buttons stay intact",
                  "state": "Keep v3",
                  "group": "D5"
                },
                {
                  "id": "REQ-D6-8",
                  "title": "Existing v3 buttons stay intact",
                  "state": "Keep v3",
                  "group": "D6"
                }
              ],
              "removal": [
                {
                  "id": "REQ-D1-7",
                  "title": "Unhook flagged Intoxication Severity & Withdrawal Risk from v4",
                  "state": "Retire v4",
                  "group": "D1"
                },
                {
                  "id": "REQ-D2-1",
                  "title": "Psychotropic Med History moves to D3",
                  "state": "Move",
                  "group": "D2"
                },
                {
                  "id": "REQ-D2-6",
                  "title": "Retire the single 0–4 rating from v4",
                  "state": "Retire v4",
                  "group": "D2"
                },
                {
                  "id": "REQ-D3-2",
                  "title": "Psychotropic Med History arrives from D2",
                  "state": "Move",
                  "group": "D3"
                },
                {
                  "id": "REQ-D4-2",
                  "title": "Relapse History arrives from D5",
                  "state": "Move",
                  "group": "D4"
                },
                {
                  "id": "REQ-D4-6",
                  "title": "Retire risk of refusal / non-compliance 0–4",
                  "state": "Retire v4",
                  "group": "D4"
                },
                {
                  "id": "REQ-D5-1",
                  "title": "Relapse History leaves D5",
                  "state": "Move",
                  "group": "D5"
                },
                {
                  "id": "REQ-D5-2",
                  "title": "CD Residential Treatment History leaves D5 in v4",
                  "state": "Move",
                  "group": "D5"
                },
                {
                  "id": "REQ-D5-3",
                  "title": "Support System / Social Setting arrives from D6",
                  "state": "Move",
                  "group": "D5"
                },
                {
                  "id": "REQ-D5-9",
                  "title": "Retire Risk of Relapse 0–4 from v4",
                  "state": "Retire v4",
                  "group": "D5"
                },
                {
                  "id": "REQ-D6-1",
                  "title": "Support System / Social Setting leaves D6",
                  "state": "Move",
                  "group": "D6"
                },
                {
                  "id": "REQ-D6-7",
                  "title": "Retire the 0–4 social environment rating from v4",
                  "state": "Retire v4",
                  "group": "D6"
                }
              ],
              "open": [
                {
                  "id": "REQ-D1-1",
                  "title": "Intoxication & Associated Risks rating",
                  "state": "To build",
                  "group": "D1"
                },
                {
                  "id": "REQ-D1-2",
                  "title": "Withdrawal & Associated Risks rating",
                  "state": "To build",
                  "group": "D1"
                },
                {
                  "id": "REQ-D1-3",
                  "title": "Addiction Medication Needs Risk rating",
                  "state": "To build",
                  "group": "D1"
                },
                {
                  "id": "REQ-D1-4",
                  "title": "Addiction Medication Needs (MOUD) button",
                  "state": "To build",
                  "group": "D1"
                },
                {
                  "id": "REQ-D1-8",
                  "title": "Shrub picker redesign & edition selection",
                  "state": "Open",
                  "group": "D1"
                },
                {
                  "id": "REQ-D2-2",
                  "title": "Add Vital Signs",
                  "state": "To build",
                  "group": "D2"
                },
                {
                  "id": "REQ-D2-3",
                  "title": "Pregnancy Screen",
                  "state": "To build",
                  "group": "D2"
                },
                {
                  "id": "REQ-D2-4",
                  "title": "Physical Health Concerns Risk rating",
                  "state": "To build",
                  "group": "D2"
                },
                {
                  "id": "REQ-D2-5",
                  "title": "Pregnancy-related Concerns Risk rating",
                  "state": "To build",
                  "group": "D2"
                },
                {
                  "id": "REQ-D2-7",
                  "title": "Medical Screen",
                  "state": "To build",
                  "group": "D2"
                },
                {
                  "id": "REQ-D2-10",
                  "title": "Sleep Problems",
                  "state": "To build",
                  "group": "D2"
                },
                {
                  "id": "REQ-D3-3",
                  "title": "Cognitive / Persistent Disability Screen",
                  "state": "To build",
                  "group": "D3"
                },
                {
                  "id": "REQ-D3-4",
                  "title": "COE Determination",
                  "state": "To build",
                  "group": "D3"
                },
                {
                  "id": "REQ-D3-5",
                  "title": "Active Psychiatric Symptoms Risk rating",
                  "state": "To build",
                  "group": "D3"
                },
                {
                  "id": "REQ-D3-6",
                  "title": "Persistent Disability Risk rating",
                  "state": "To build",
                  "group": "D3"
                },
                {
                  "id": "REQ-D3-7",
                  "title": "Cognitive Screening",
                  "state": "To build",
                  "group": "D3"
                },
                {
                  "id": "REQ-D3-8",
                  "title": "Trauma & PTSD Screening",
                  "state": "To build",
                  "group": "D3"
                },
                {
                  "id": "REQ-D3-10",
                  "title": "Mental Status Exam",
                  "state": "To build",
                  "group": "D3"
                },
                {
                  "id": "REQ-D4-3",
                  "title": "Likelihood of Risky Substance Use Risk rating",
                  "state": "To build",
                  "group": "D4"
                },
                {
                  "id": "REQ-D4-4",
                  "title": "Likelihood of Risky SUD-related Behaviors Risk rating",
                  "state": "To build",
                  "group": "D4"
                },
                {
                  "id": "REQ-D4-5",
                  "title": "Imminent Consequences (Appendix C)",
                  "state": "To build",
                  "group": "D4"
                },
                {
                  "id": "REQ-D4-7",
                  "title": "Risky Behaviors Checklist",
                  "state": "To build",
                  "group": "D4"
                },
                {
                  "id": "REQ-D5-4",
                  "title": "Housing & Safety Screen",
                  "state": "To build",
                  "group": "D5"
                },
                {
                  "id": "REQ-D5-5",
                  "title": "Functional Impairment (Appendix D)",
                  "state": "To build",
                  "group": "D5"
                },
                {
                  "id": "REQ-D5-6",
                  "title": "Ability to Function Effectively Risk rating",
                  "state": "To build",
                  "group": "D5"
                },
                {
                  "id": "REQ-D5-7",
                  "title": "Safety in Environment Risk rating",
                  "state": "To build",
                  "group": "D5"
                },
                {
                  "id": "REQ-D5-8",
                  "title": "Support in Environment Risk rating",
                  "state": "To build",
                  "group": "D5"
                },
                {
                  "id": "REQ-D5-12",
                  "title": "Recovery Strengths & Resources",
                  "state": "To build",
                  "group": "D5"
                },
                {
                  "id": "REQ-D5-13",
                  "title": "Social Determinants of Health",
                  "state": "To build",
                  "group": "D5"
                },
                {
                  "id": "REQ-D6-3",
                  "title": "Willingness & Ability to Attend button",
                  "state": "To build",
                  "group": "D6"
                },
                {
                  "id": "REQ-D6-4",
                  "title": "Barriers to Participation",
                  "state": "To build",
                  "group": "D6"
                },
                {
                  "id": "REQ-D6-5",
                  "title": "Readiness / Motivation Change",
                  "state": "To build",
                  "group": "D6"
                },
                {
                  "id": "REQ-D6-6",
                  "title": "Recommended vs. Selected LOC",
                  "state": "To build",
                  "group": "D6"
                },
                {
                  "id": "REQ-D6-9",
                  "title": "Preferences & Treatment Goals",
                  "state": "To build",
                  "group": "D6"
                },
                {
                  "id": "REQ-D6-10",
                  "title": "Cultural & Linguistic Needs",
                  "state": "To build",
                  "group": "D6"
                },
                {
                  "id": "REQ-D6-11",
                  "title": "Shared Decision-Making Notes",
                  "state": "To build",
                  "group": "D6"
                },
                {
                  "id": "REQ-D6-12",
                  "title": "Engagement & discrepancy questions",
                  "state": "To build",
                  "group": "D6"
                },
                {
                  "id": "REQ-R-7",
                  "title": "Recommendation tab layout & control placement",
                  "state": "To build",
                  "group": "REC"
                }
              ],
              "missing": []
            }
          },
          "tickets": {
            "total": 0,
            "percent": 0,
            "todo": 0,
            "in_progress": 0,
            "done": 0
          },
          "open_tickets": [],
          "rag": "amber",
          "flags": [
            {
              "level": "amber",
              "text": "50 requirements, no tickets created yet"
            },
            {
              "level": "info",
              "text": "Target date is a placeholder, not confirmed"
            }
          ],
          "complete": false
        },
        {
          "id": "M2",
          "claim": "The 4th Edition is as workable as the 3rd",
          "why": "M1 proves it works. M2 makes it something a clinician would choose over paper. This is where v4 stops being a pilot and starts being the product.",
          "must_be_true": [
            "Anything that gets pushed from Milestone 1 — functionality missed in M1, or things found in M1 that we agreed could be done later\n",
            "Update the Create Custom Button and Column on the v4 dimension tabs",
            "Shrub tree redesign: layout, grouping, and how selections read back into the note\n",
            "Points to Consider available on each dimension",
            "Notepad Redesign"
          ],
          "target": "2026-10-17",
          "target_confirmed": false,
          "days_left": 52,
          "notes": [
            "REQ-R-4 (ratings roll-up & Level-of-Care determination) is the licensing-gated piece. Deliberately not in M1."
          ],
          "open_questions": [],
          "reqs": {
            "total": 7,
            "no_work": 0,
            "removal": 0,
            "open": 7,
            "work": 7,
            "missing": 0,
            "items": {
              "done": [],
              "removal": [],
              "open": [
                {
                  "id": "REQ-D1-5",
                  "title": "Points to Consider",
                  "state": "To build",
                  "group": "D1"
                },
                {
                  "id": "REQ-D2-8",
                  "title": "Points to Consider",
                  "state": "To build",
                  "group": "D2"
                },
                {
                  "id": "REQ-D3-9",
                  "title": "Points to Consider",
                  "state": "To build",
                  "group": "D3"
                },
                {
                  "id": "REQ-D4-1",
                  "title": "Points to Consider",
                  "state": "To build",
                  "group": "D4"
                },
                {
                  "id": "REQ-D5-10",
                  "title": "Points to Consider",
                  "state": "To build",
                  "group": "D5"
                },
                {
                  "id": "REQ-D6-2",
                  "title": "Points to Consider",
                  "state": "To build",
                  "group": "D6"
                },
                {
                  "id": "REQ-R-4",
                  "title": "Dimension ratings roll-up & Level-of-Care determination",
                  "state": "Engine",
                  "group": "REC"
                }
              ],
              "missing": []
            }
          },
          "tickets": {
            "total": 0,
            "percent": 0,
            "todo": 0,
            "in_progress": 0,
            "done": 0
          },
          "open_tickets": [],
          "rag": "amber",
          "flags": [
            {
              "level": "amber",
              "text": "7 requirements, no tickets created yet"
            },
            {
              "level": "info",
              "text": "Target date is a placeholder, not confirmed"
            }
          ],
          "complete": false
        },
        {
          "id": "M3",
          "claim": "The surrounding screens catch up",
          "why": "The assessment doesn't live alone. Everything adjacent gets brought up to the same standard.",
          "must_be_true": [
            "Final UI/UX Polish",
            "Vital Signs redesign",
            "Diagnosis and Service Codes redesign"
          ],
          "target": "2026-11-14",
          "target_confirmed": false,
          "days_left": 80,
          "notes": [
            "No requirements map here yet. asam-reqs.js covers the assessment itself, not the surrounding screens — so M3's scope exists only as prose in the PRD. This is a real gap, not a mapping error."
          ],
          "open_questions": [],
          "reqs": {
            "total": 0,
            "no_work": 0,
            "removal": 0,
            "open": 0,
            "work": 0,
            "missing": 0,
            "items": {
              "done": [],
              "removal": [],
              "open": [],
              "missing": []
            }
          },
          "tickets": {
            "total": 0,
            "percent": 0,
            "todo": 0,
            "in_progress": 0,
            "done": 0
          },
          "open_tickets": [],
          "rag": "green",
          "flags": [
            {
              "level": "info",
              "text": "No requirements mapped — scope exists only as prose in the PRD"
            },
            {
              "level": "info",
              "text": "Target date is a placeholder, not confirmed"
            }
          ],
          "complete": false
        }
      ],
      "current": 0,
      "rag": "amber",
      "flags": [],
      "span": {
        "start": "2026-08-26",
        "end": "2026-11-14",
        "planned": true
      },
      "events": [
        {
          "date": "2026-09-19",
          "kind": "milestone",
          "key": "M1",
          "label": "A pilot practice can complete a 4th Edition assessment",
          "firm": false
        },
        {
          "date": "2026-10-17",
          "kind": "milestone",
          "key": "M2",
          "label": "The 4th Edition is as workable as the 3rd",
          "firm": false
        },
        {
          "date": "2026-11-14",
          "kind": "milestone",
          "key": "M3",
          "label": "The surrounding screens catch up",
          "firm": false
        }
      ],
      "tickets": {
        "total": 0,
        "percent": 0,
        "todo": 0,
        "in_progress": 0,
        "done": 0
      },
      "open_tickets": [],
      "unmapped_tickets": [],
      "unmapped_reqs": [],
      "risks": [
        {
          "text": "Details internal",
          "severity": "high",
          "redacted": true
        },
        {
          "text": "Which payers, states, or accreditation bodies require the 4th Edition, affecting how many practices, by when. Biggest gap in this PRD; everything else is downstream of it.",
          "severity": "high",
          "owner": "Christian Carlstrom",
          "redacted": false
        },
        {
          "text": "Is the GAIN button retired, kept for both, or flagged? October notes it is optional under the 4th Edition but leaves the product decision to us.",
          "severity": "medium",
          "owner": "Christian Carlstrom",
          "redacted": false
        },
        {
          "text": "Is a practice-wide flag sufficient?",
          "severity": "medium",
          "owner": "Franco Agresta / Christian Carlstrom",
          "redacted": false
        },
        {
          "text": "What happens if a practice flips the flag mid-note?",
          "severity": "medium",
          "owner": "Franco Agresta",
          "redacted": false
        }
      ]
    },
    {
      "key": "go-sessions",
      "name": "Go Sessions — In-Office Patient Intake",
      "short": "Go Sessions",
      "blurb": "Staff-controlled digital intake on a device in the waiting room, replacing the Office Ally intake flow.",
      "owner": "Christian Carlstrom",
      "eng": null,
      "status": "In Development",
      "prd": {
        "title": "PRD: Staff-Controlled In-Office Digital Intake",
        "url": "https://docs.google.com/spreadsheets/d/1KX0O4ZBLDKa_L0oWVmLV2nLFULcyp65h5x37ERHqgy4/edit",
        "note": "Authored as a spreadsheet rather than the standard PRD template, and owned by Mark Lindell.\n"
      },
      "prototype": null,
      "epic": "CLN-3809",
      "epic_url": "https://icanotes.atlassian.net/browse/CLN-3809",
      "milestones": [],
      "current": -1,
      "rag": "green",
      "flags": [
        {
          "level": "info",
          "text": "No milestones defined — showing epic rollup only, so there is no plan to measure delivery against"
        }
      ],
      "span": {
        "start": "2026-05-29",
        "end": "2026-08-26"
      },
      "events": [
        {
          "date": "2026-06-02",
          "kind": "resolved",
          "key": "CLN-3816",
          "label": "Identify UC collision with the reuse of form_patient table"
        },
        {
          "date": "2026-07-01",
          "kind": "resolved",
          "key": "DO-12381",
          "label": "Deploy new UI and Backend"
        },
        {
          "date": "2026-07-14",
          "kind": "resolved",
          "key": "CLN-3824",
          "label": "Bootstrap the new interfaces, models and projects"
        },
        {
          "date": "2026-08-11",
          "kind": "resolved",
          "key": "CLN-3817",
          "label": "Intake Session Management: UI Accordion"
        },
        {
          "date": "2026-08-11",
          "kind": "resolved",
          "key": "CLN-3821",
          "label": "Welcome / Default  Intake page"
        },
        {
          "date": "2026-08-13",
          "kind": "resolved",
          "key": "CLN-3893",
          "label": "Create a new permission"
        },
        {
          "date": "2026-08-17",
          "kind": "resolved",
          "key": "CLN-3822",
          "label": "Intake Session Execution Flow"
        },
        {
          "date": "2026-08-21",
          "kind": "bug",
          "count": 8,
          "key": null,
          "keys": [
            "CLN-4039",
            "CLN-4040",
            "CLN-4041",
            "CLN-4042",
            "CLN-4043",
            "CLN-4044",
            "CLN-4045",
            "CLN-4047"
          ],
          "label": "8 bugs filed",
          "through": "2026-08-25"
        }
      ],
      "tickets": {
        "total": 28,
        "percent": 25,
        "todo": 20,
        "in_progress": 1,
        "done": 7
      },
      "open_tickets": [
        {
          "key": "CLN-3980",
          "url": "https://icanotes.atlassian.net/browse/CLN-3980",
          "summary": "UI/UX Polish",
          "status": "Testing",
          "category": "indeterminate",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-08-03",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4039",
          "url": "https://icanotes.atlassian.net/browse/CLN-4039",
          "summary": "[Go Session: Desktop] Limit on Forms qty needs a designated error prompt",
          "status": "Open",
          "category": "new",
          "type": "Bug",
          "assignee": null,
          "labels": [],
          "created": "2026-08-21",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4040",
          "url": "https://icanotes.atlassian.net/browse/CLN-4040",
          "summary": "[Go session] Packages are not order alphabetically in \"select forms and assessment\" modal",
          "status": "Open",
          "category": "new",
          "type": "Bug",
          "assignee": null,
          "labels": [],
          "created": "2026-08-21",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4041",
          "url": "https://icanotes.atlassian.net/browse/CLN-4041",
          "summary": "[Go session: Desktop] Session creation fails when package selected contains form template ",
          "status": "Open",
          "category": "new",
          "type": "Bug",
          "assignee": null,
          "labels": [],
          "created": "2026-08-21",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4042",
          "url": "https://icanotes.atlassian.net/browse/CLN-4042",
          "summary": "[Go Session: Desktop] Go Session Forms are accessible in Client Portal",
          "status": "Open",
          "category": "new",
          "type": "Bug",
          "assignee": null,
          "labels": [],
          "created": "2026-08-21",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4043",
          "url": "https://icanotes.atlassian.net/browse/CLN-4043",
          "summary": "Go Session | Clicking on the Refresh button after having submitted all forms doesn't redirect user to Homepage",
          "status": "Open",
          "category": "new",
          "type": "Bug",
          "assignee": null,
          "labels": [],
          "created": "2026-08-24",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4044",
          "url": "https://icanotes.atlassian.net/browse/CLN-4044",
          "summary": "Go Session | User with 0 forms gets taken to Something Went Wrong page",
          "status": "Open",
          "category": "new",
          "type": "Bug",
          "assignee": null,
          "labels": [],
          "created": "2026-08-24",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4045",
          "url": "https://icanotes.atlassian.net/browse/CLN-4045",
          "summary": "Go Session | Incorrect message is displayed when submitting a Go Session that was canceled by creating a new session",
          "status": "Open",
          "category": "new",
          "type": "Bug",
          "assignee": null,
          "labels": [],
          "created": "2026-08-24",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4047",
          "url": "https://icanotes.atlassian.net/browse/CLN-4047",
          "summary": "Go Session |Completed Go Session QR Code Remains Displayed Until Page Refresh",
          "status": "Open",
          "category": "new",
          "type": "Bug",
          "assignee": null,
          "labels": [],
          "created": "2026-08-25",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3837",
          "url": "https://icanotes.atlassian.net/browse/CLN-3837",
          "summary": "Check API for camera and QR from chrome/safari",
          "status": "Open",
          "category": "new",
          "type": "Spike",
          "assignee": null,
          "labels": [],
          "created": "2026-06-05",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3839",
          "url": "https://icanotes.atlassian.net/browse/CLN-3839",
          "summary": "Go Frontend Inactivity Daemon",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-06-05",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3840",
          "url": "https://icanotes.atlassian.net/browse/CLN-3840",
          "summary": "Remove navigation back to the session creation",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-06-05",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3905",
          "url": "https://icanotes.atlassian.net/browse/CLN-3905",
          "summary": "Add Go-Session status pill for form completion",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-07-07",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3906",
          "url": "https://icanotes.atlassian.net/browse/CLN-3906",
          "summary": "[Spike] - Verify form-completed notification fires for Go-Sessions intake forms",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-07-07",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3907",
          "url": "https://icanotes.atlassian.net/browse/CLN-3907",
          "summary": "Go Sessions Report — session history by client",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-07-07",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3908",
          "url": "https://icanotes.atlassian.net/browse/CLN-3908",
          "summary": "Add \"Go Sessions\" permission category to Roles & Permissions",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-07-07",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3915",
          "url": "https://icanotes.atlassian.net/browse/CLN-3915",
          "summary": "General cleanup",
          "status": "Open",
          "category": "new",
          "type": "Task",
          "assignee": null,
          "labels": [],
          "created": "2026-07-09",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3924",
          "url": "https://icanotes.atlassian.net/browse/CLN-3924",
          "summary": "Send Go Session Link, Select or add contact",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-07-13",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3945",
          "url": "https://icanotes.atlassian.net/browse/CLN-3945",
          "summary": "Concurrent session handling — same intake session opened on multiple devices",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-07-21",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3991",
          "url": "https://icanotes.atlassian.net/browse/CLN-3991",
          "summary": "End/Destroy Session Logic (To be or Not to be Implemented?)",
          "status": "Open",
          "category": "new",
          "type": "Task",
          "assignee": null,
          "labels": [],
          "created": "2026-08-05",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4026",
          "url": "https://icanotes.atlassian.net/browse/CLN-4026",
          "summary": "In-Progress handling on Admin ui",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-08-17",
          "resolved": null,
          "updated": null
        }
      ],
      "unmapped_tickets": [
        {
          "key": "CLN-3816",
          "url": "https://icanotes.atlassian.net/browse/CLN-3816",
          "summary": "Identify UC collision with the reuse of form_patient table",
          "status": "Closed",
          "category": "done",
          "type": "Spike",
          "assignee": null,
          "labels": [],
          "created": "2026-05-29",
          "resolved": "2026-06-02",
          "updated": null
        },
        {
          "key": "CLN-3817",
          "url": "https://icanotes.atlassian.net/browse/CLN-3817",
          "summary": "Intake Session Management: UI Accordion",
          "status": "Closed",
          "category": "done",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-05-29",
          "resolved": "2026-08-11",
          "updated": null
        },
        {
          "key": "DO-12381",
          "url": "https://icanotes.atlassian.net/browse/DO-12381",
          "summary": "Deploy new UI and Backend",
          "status": "Closed",
          "category": "done",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-05-29",
          "resolved": "2026-07-01",
          "updated": null
        },
        {
          "key": "CLN-3821",
          "url": "https://icanotes.atlassian.net/browse/CLN-3821",
          "summary": "Welcome / Default  Intake page",
          "status": "Closed",
          "category": "done",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-05-29",
          "resolved": "2026-08-11",
          "updated": null
        },
        {
          "key": "CLN-3822",
          "url": "https://icanotes.atlassian.net/browse/CLN-3822",
          "summary": "Intake Session Execution Flow",
          "status": "Closed",
          "category": "done",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-06-01",
          "resolved": "2026-08-17",
          "updated": null
        },
        {
          "key": "CLN-3824",
          "url": "https://icanotes.atlassian.net/browse/CLN-3824",
          "summary": "Bootstrap the new interfaces, models and projects",
          "status": "Closed",
          "category": "done",
          "type": "Dev Improvement",
          "assignee": null,
          "labels": [],
          "created": "2026-06-01",
          "resolved": "2026-07-14",
          "updated": null
        },
        {
          "key": "CLN-3837",
          "url": "https://icanotes.atlassian.net/browse/CLN-3837",
          "summary": "Check API for camera and QR from chrome/safari",
          "status": "Open",
          "category": "new",
          "type": "Spike",
          "assignee": null,
          "labels": [],
          "created": "2026-06-05",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3839",
          "url": "https://icanotes.atlassian.net/browse/CLN-3839",
          "summary": "Go Frontend Inactivity Daemon",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-06-05",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3840",
          "url": "https://icanotes.atlassian.net/browse/CLN-3840",
          "summary": "Remove navigation back to the session creation",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-06-05",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3893",
          "url": "https://icanotes.atlassian.net/browse/CLN-3893",
          "summary": "Create a new permission",
          "status": "Resolved",
          "category": "done",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-07-02",
          "resolved": "2026-08-13",
          "updated": null
        },
        {
          "key": "CLN-3905",
          "url": "https://icanotes.atlassian.net/browse/CLN-3905",
          "summary": "Add Go-Session status pill for form completion",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-07-07",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3906",
          "url": "https://icanotes.atlassian.net/browse/CLN-3906",
          "summary": "[Spike] - Verify form-completed notification fires for Go-Sessions intake forms",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-07-07",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3907",
          "url": "https://icanotes.atlassian.net/browse/CLN-3907",
          "summary": "Go Sessions Report — session history by client",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-07-07",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3908",
          "url": "https://icanotes.atlassian.net/browse/CLN-3908",
          "summary": "Add \"Go Sessions\" permission category to Roles & Permissions",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-07-07",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3915",
          "url": "https://icanotes.atlassian.net/browse/CLN-3915",
          "summary": "General cleanup",
          "status": "Open",
          "category": "new",
          "type": "Task",
          "assignee": null,
          "labels": [],
          "created": "2026-07-09",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3924",
          "url": "https://icanotes.atlassian.net/browse/CLN-3924",
          "summary": "Send Go Session Link, Select or add contact",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-07-13",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3945",
          "url": "https://icanotes.atlassian.net/browse/CLN-3945",
          "summary": "Concurrent session handling — same intake session opened on multiple devices",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-07-21",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3980",
          "url": "https://icanotes.atlassian.net/browse/CLN-3980",
          "summary": "UI/UX Polish",
          "status": "Testing",
          "category": "indeterminate",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-08-03",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3991",
          "url": "https://icanotes.atlassian.net/browse/CLN-3991",
          "summary": "End/Destroy Session Logic (To be or Not to be Implemented?)",
          "status": "Open",
          "category": "new",
          "type": "Task",
          "assignee": null,
          "labels": [],
          "created": "2026-08-05",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4026",
          "url": "https://icanotes.atlassian.net/browse/CLN-4026",
          "summary": "In-Progress handling on Admin ui",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-08-17",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4039",
          "url": "https://icanotes.atlassian.net/browse/CLN-4039",
          "summary": "[Go Session: Desktop] Limit on Forms qty needs a designated error prompt",
          "status": "Open",
          "category": "new",
          "type": "Bug",
          "assignee": null,
          "labels": [],
          "created": "2026-08-21",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4040",
          "url": "https://icanotes.atlassian.net/browse/CLN-4040",
          "summary": "[Go session] Packages are not order alphabetically in \"select forms and assessment\" modal",
          "status": "Open",
          "category": "new",
          "type": "Bug",
          "assignee": null,
          "labels": [],
          "created": "2026-08-21",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4041",
          "url": "https://icanotes.atlassian.net/browse/CLN-4041",
          "summary": "[Go session: Desktop] Session creation fails when package selected contains form template ",
          "status": "Open",
          "category": "new",
          "type": "Bug",
          "assignee": null,
          "labels": [],
          "created": "2026-08-21",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4042",
          "url": "https://icanotes.atlassian.net/browse/CLN-4042",
          "summary": "[Go Session: Desktop] Go Session Forms are accessible in Client Portal",
          "status": "Open",
          "category": "new",
          "type": "Bug",
          "assignee": null,
          "labels": [],
          "created": "2026-08-21",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4043",
          "url": "https://icanotes.atlassian.net/browse/CLN-4043",
          "summary": "Go Session | Clicking on the Refresh button after having submitted all forms doesn't redirect user to Homepage",
          "status": "Open",
          "category": "new",
          "type": "Bug",
          "assignee": null,
          "labels": [],
          "created": "2026-08-24",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4044",
          "url": "https://icanotes.atlassian.net/browse/CLN-4044",
          "summary": "Go Session | User with 0 forms gets taken to Something Went Wrong page",
          "status": "Open",
          "category": "new",
          "type": "Bug",
          "assignee": null,
          "labels": [],
          "created": "2026-08-24",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4045",
          "url": "https://icanotes.atlassian.net/browse/CLN-4045",
          "summary": "Go Session | Incorrect message is displayed when submitting a Go Session that was canceled by creating a new session",
          "status": "Open",
          "category": "new",
          "type": "Bug",
          "assignee": null,
          "labels": [],
          "created": "2026-08-24",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4047",
          "url": "https://icanotes.atlassian.net/browse/CLN-4047",
          "summary": "Go Session |Completed Go Session QR Code Remains Displayed Until Page Refresh",
          "status": "Open",
          "category": "new",
          "type": "Bug",
          "assignee": null,
          "labels": [],
          "created": "2026-08-25",
          "resolved": null,
          "updated": null
        }
      ],
      "unmapped_reqs": [],
      "risks": []
    },
    {
      "key": "zoho-one-provisioning",
      "name": "Product-Led Provisioning in Zoho One",
      "short": "Zoho One Provisioning",
      "blurb": "A customer signing up product-led is created and can self-subscribe in Zoho One with no manual step, and existing product-led customers migrate across automatically.",
      "owner": "Christian Carlstrom",
      "eng": null,
      "status": "In Development",
      "prd": null,
      "prototype": null,
      "epic": "CLN-3764",
      "epic_url": "https://icanotes.atlassian.net/browse/CLN-3764",
      "milestones": [],
      "current": -1,
      "rag": "green",
      "flags": [
        {
          "level": "info",
          "text": "No milestones defined — showing epic rollup only, so there is no plan to measure delivery against"
        },
        {
          "level": "info",
          "text": "No PRD linked"
        }
      ],
      "span": {
        "start": "2026-05-15",
        "end": "2026-08-26"
      },
      "events": [
        {
          "date": "2026-06-23",
          "kind": "resolved",
          "key": "CLN-3780",
          "label": "Create new Cx in Zoho one at signup"
        },
        {
          "date": "2026-07-24",
          "kind": "resolved",
          "key": "CLN-3781",
          "label": "Create a new tenant in zoho one"
        },
        {
          "date": "2026-08-04",
          "kind": "resolved",
          "key": "CLN-3946",
          "label": "Investigate how to migrate existing product led customers to new zoho instance"
        },
        {
          "date": "2026-08-05",
          "kind": "resolved",
          "key": "CLN-3828",
          "label": "Add new error mapping to Zoho Integrations Error"
        },
        {
          "date": "2026-08-12",
          "kind": "resolved",
          "key": "CLN-3783",
          "label": "Allow Zoho One PL Customers to Self-Subscribe"
        },
        {
          "date": "2026-08-20",
          "kind": "bug",
          "count": 1,
          "key": "CLN-4034",
          "keys": [
            "CLN-4034"
          ],
          "label": "User business rules can’t be enabled for “none” billing model user when practice is going to be related to zoho one",
          "through": "2026-08-20"
        }
      ],
      "tickets": {
        "total": 9,
        "percent": 56,
        "todo": 4,
        "in_progress": 0,
        "done": 5
      },
      "open_tickets": [
        {
          "key": "CLN-4034",
          "url": "https://icanotes.atlassian.net/browse/CLN-4034",
          "summary": "User business rules can’t be enabled for “none” billing model user when practice is going to be related to zoho one",
          "status": "Open",
          "category": "new",
          "type": "Bug",
          "assignee": null,
          "labels": [],
          "created": "2026-08-20",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3794",
          "url": "https://icanotes.atlassian.net/browse/CLN-3794",
          "summary": "SMS: Automated Usage Tracking & Usage-Based Billing for SMS",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-05-22",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4013",
          "url": "https://icanotes.atlassian.net/browse/CLN-4013",
          "summary": "Automate Zoho One migration via Multica",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-08-12",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4018",
          "url": "https://icanotes.atlassian.net/browse/CLN-4018",
          "summary": "Spike - Automate Zoho One migration via Multica",
          "status": "Open",
          "category": "new",
          "type": "Spike",
          "assignee": null,
          "labels": [],
          "created": "2026-08-13",
          "resolved": null,
          "updated": null
        }
      ],
      "unmapped_tickets": [
        {
          "key": "CLN-3780",
          "url": "https://icanotes.atlassian.net/browse/CLN-3780",
          "summary": "Create new Cx in Zoho one at signup",
          "status": "Closed",
          "category": "done",
          "type": "Spike",
          "assignee": null,
          "labels": [],
          "created": "2026-05-15",
          "resolved": "2026-06-23",
          "updated": null
        },
        {
          "key": "CLN-3781",
          "url": "https://icanotes.atlassian.net/browse/CLN-3781",
          "summary": "Create a new tenant in zoho one",
          "status": "Closed",
          "category": "done",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-05-15",
          "resolved": "2026-07-24",
          "updated": null
        },
        {
          "key": "CLN-3783",
          "url": "https://icanotes.atlassian.net/browse/CLN-3783",
          "summary": "Allow Zoho One PL Customers to Self-Subscribe",
          "status": "Closed",
          "category": "done",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-05-18",
          "resolved": "2026-08-12",
          "updated": null
        },
        {
          "key": "CLN-3794",
          "url": "https://icanotes.atlassian.net/browse/CLN-3794",
          "summary": "SMS: Automated Usage Tracking & Usage-Based Billing for SMS",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-05-22",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-3828",
          "url": "https://icanotes.atlassian.net/browse/CLN-3828",
          "summary": "Add new error mapping to Zoho Integrations Error",
          "status": "Closed",
          "category": "done",
          "type": "Dev Improvement",
          "assignee": null,
          "labels": [],
          "created": "2026-06-02",
          "resolved": "2026-08-05",
          "updated": null
        },
        {
          "key": "CLN-3946",
          "url": "https://icanotes.atlassian.net/browse/CLN-3946",
          "summary": "Investigate how to migrate existing product led customers to new zoho instance",
          "status": "Closed",
          "category": "done",
          "type": "Spike",
          "assignee": null,
          "labels": [],
          "created": "2026-07-22",
          "resolved": "2026-08-04",
          "updated": null
        },
        {
          "key": "CLN-4013",
          "url": "https://icanotes.atlassian.net/browse/CLN-4013",
          "summary": "Automate Zoho One migration via Multica",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-08-12",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4018",
          "url": "https://icanotes.atlassian.net/browse/CLN-4018",
          "summary": "Spike - Automate Zoho One migration via Multica",
          "status": "Open",
          "category": "new",
          "type": "Spike",
          "assignee": null,
          "labels": [],
          "created": "2026-08-13",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4034",
          "url": "https://icanotes.atlassian.net/browse/CLN-4034",
          "summary": "User business rules can’t be enabled for “none” billing model user when practice is going to be related to zoho one",
          "status": "Open",
          "category": "new",
          "type": "Bug",
          "assignee": null,
          "labels": [],
          "created": "2026-08-20",
          "resolved": null,
          "updated": null
        }
      ],
      "unmapped_reqs": [],
      "risks": []
    },
    {
      "key": "note-ownership",
      "name": "Historical Note Ownership on Clinician Transfer",
      "short": "Note Ownership",
      "blurb": "A note keeps the clinician who wrote it. Deactivating a clinician stops silently reassigning their signed work, and inactive clinicians stay visible where the record depends on them.",
      "owner": "Christian Carlstrom",
      "eng": null,
      "status": "In Development",
      "prd": null,
      "prototype": null,
      "epic": "CLN-3516",
      "epic_url": "https://icanotes.atlassian.net/browse/CLN-3516",
      "milestones": [],
      "current": -1,
      "rag": "green",
      "flags": [
        {
          "level": "info",
          "text": "No milestones defined — showing epic rollup only, so there is no plan to measure delivery against"
        },
        {
          "level": "info",
          "text": "No PRD linked"
        }
      ],
      "span": {
        "start": "2026-08-14",
        "end": "2026-08-26"
      },
      "events": [],
      "tickets": {
        "total": 3,
        "percent": 0,
        "todo": 1,
        "in_progress": 2,
        "done": 0
      },
      "open_tickets": [
        {
          "key": "CLN-4020",
          "url": "https://icanotes.atlassian.net/browse/CLN-4020",
          "summary": "Show inactive/deactivated clinicians in note footer (Historical Notes, Assessments/Evaluations, Treatment Plans)",
          "status": "Review",
          "category": "indeterminate",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-08-14",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4022",
          "url": "https://icanotes.atlassian.net/browse/CLN-4022",
          "summary": "Stop auto-transferring note-level assigned clinician on deactivation/transfer",
          "status": "Review",
          "category": "indeterminate",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-08-14",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4021",
          "url": "https://icanotes.atlassian.net/browse/CLN-4021",
          "summary": "Show inactive clinicians in dashboard",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-08-14",
          "resolved": null,
          "updated": null
        }
      ],
      "unmapped_tickets": [
        {
          "key": "CLN-4020",
          "url": "https://icanotes.atlassian.net/browse/CLN-4020",
          "summary": "Show inactive/deactivated clinicians in note footer (Historical Notes, Assessments/Evaluations, Treatment Plans)",
          "status": "Review",
          "category": "indeterminate",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-08-14",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4021",
          "url": "https://icanotes.atlassian.net/browse/CLN-4021",
          "summary": "Show inactive clinicians in dashboard",
          "status": "Open",
          "category": "new",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-08-14",
          "resolved": null,
          "updated": null
        },
        {
          "key": "CLN-4022",
          "url": "https://icanotes.atlassian.net/browse/CLN-4022",
          "summary": "Stop auto-transferring note-level assigned clinician on deactivation/transfer",
          "status": "Review",
          "category": "indeterminate",
          "type": "Story",
          "assignee": null,
          "labels": [],
          "created": "2026-08-14",
          "resolved": null,
          "updated": null
        }
      ],
      "unmapped_reqs": [],
      "risks": []
    }
  ]
};
